# Earth Analytics Bootcamp - Practice Activity on Data Structures
**Author** Nan Rosenbloom

#### Import the software packages that I need.  These include os, pandas, numpy, matplotlib, and urllib.request

In [28]:
# Import the packages I'll need.
import os
import pandas as pd
import numpy as np
import matplotlib as plt
import urllib.request

# print message after packages imported successfully
print("import of packages successful")


import of packages successful


#### Create a Python list of the average monthly temperatures, and a second list of the corresponding names of the months.  Notice that June and July are missing.

In [2]:
#  create a Python list of the average monthly temperature (C) in Boulder.
months = ["Jan","Feb","Mar","Apr","May","Aug","Sept","Oct","Nov","Dec"]
temps = [0.0,2.00,5.0,9.56,14.39,21.72,16.72,11.61,4.89,0.99]

#### Check what months are missing.

In [30]:
# print the contents of the months list
print(months)

['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Aug', 'Sept', 'Oct', 'Nov', 'Dec']


In [31]:
# print the contents of the temperatures list
print(temps)

[0.0, 2.0, 5.0, 9.56, 14.39, 21.72, 16.72, 11.61, 4.89, 0.99]


In [32]:
# check the length of the months file.  Missing some months!
len(months)

10

In [33]:
len(temps)

10

#### Insert the missing months (June, July), by referencing the appropriate indexing.

In [34]:
# insert the missing months of June and July.
months.insert(5,"June")
months.insert(6,"July")

#### Print the completed month listing.

In [35]:
print(months)

['Jan', 'Feb', 'Mar', 'Apr', 'May', 'June', 'July', 'Aug', 'Sept', 'Oct', 'Nov', 'Dec']


#### Insert the missing temperate values for June and July, using the appropriate indexing (zero-based).

In [36]:
# insert the missing temperatures for the months of June and July.
temps.insert(5,19.56)
temps.insert(6,22.78)

#### Complete monthly mean temperature values (degrees C).

In [37]:
print(temps)

[0.0, 2.0, 5.0, 9.56, 14.39, 19.56, 22.78, 21.72, 16.72, 11.61, 4.89, 0.99]


#### Create a 1D array  using  numpy.array.

In [38]:
temparr = np.array([0.0, 2.0, 5.0, 9.56, 14.39, 19.56, 22.78, 21.72, 16.72, 11.61, 4.89, 0.99])

In [39]:
print(temparr)

[ 0.    2.    5.    9.56 14.39 19.56 22.78 21.72 16.72 11.61  4.89  0.99]


  #### Create a new array using the one I just created.

In [40]:
temparr2 = np.array(temparr)

In [41]:
print(temparr2)

[ 0.    2.    5.    9.56 14.39 19.56 22.78 21.72 16.72 11.61  4.89  0.99]


## Download data - 2 step process
### 1.   Set my working directory, then print working directory to confirm that it is set correctly.

In [42]:
# set the working directory to the `earth-analytics-bootcamp` directory
# replace `jpalomino` with your username here and all paths in this lesson
os.chdir("/Users/nanr/work/earth-analytics-bootcamp/")

# print the current working directory
os.getcwd()
'/Users/nanr/work/earth-analytics-bootcamp'

'/Users/nanr/work/earth-analytics-bootcamp'

### 2.  Download the data from the figshare repository.

In [43]:
# use `urllib` download files from Earth Lab figshare repository

# download .csv containing monthly average temperature for Boulder, CO
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12732467", 
                           filename = "data/avg-monthly-temp.txt")


# print message that data downloads were successful
print("datasets downloaded successfully")

datasets downloaded successfully


In [44]:
# use `urllib` download files from Earth Lab figshare repository

# download .csv containing monthly average temperature for Boulder, CO
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12732467", 
                           filename = "data/avg-monthly-temp.txt")


# print message that data downloads were successful
print("datasets downloaded successfully")

datasets downloaded successfully


In [45]:
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12565619", 
                           filename = "data/months.txt")

('data/months.txt', <http.client.HTTPMessage at 0x10e5ad550>)

In [46]:
tavg = np.loadtxt(fname="data/avg-monthly-temp.txt")

# print message that data downloads were successful
print("datasets downloaded successfully")

datasets downloaded successfully


In [26]:
print(tavg)

[ 0.    2.    5.    9.56 14.39 19.56 22.78 21.72 16.72 11.61  4.89  0.99]


In [49]:
print(type(tavg))

<class 'numpy.ndarray'>


In [63]:
mam_temp = np.array(tavg[2:5,])

In [64]:
print(mam_temp)

[ 5.    9.56 14.39]


In [65]:
son_temp = np.array(tavg[8:11,])

In [66]:
print(son_temp)

[16.72 11.61  4.89]


In [76]:
arraylist = [mam_temp,son_temp]

In [78]:
print(arraylist)

[array([ 5.  ,  9.56, 14.39]), array([16.72, 11.61,  4.89])]


In [81]:
for m in arraylist:
    mtmp = np.mean(m)
    print(mtmp)

9.65
11.073333333333332


In [91]:
mon_temp = pd.DataFrame( columns=["Months", "Temp"], data=[["January", 0.0], ["February", 2.0], ["March", 5.0],["April",9.56],["May",14.39],["June",19.56],["July",22.78],["August",21.72],["September",16.72],["October",11.61],["November",4.89],["December","0.99"]] )

In [92]:
print(mon_temp)

       Months   Temp
0     January      0
1    February      2
2       March      5
3       April   9.56
4         May  14.39
5        June  19.56
6        July  22.78
7      August  21.72
8   September  16.72
9     October  11.61
10   November   4.89
11   December   0.99


In [94]:
# use `urllib` download files from Earth Lab figshare repository

# download .csv containing monthly average temperature for Boulder, CO
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12739457", 
                           filename = "data/avg-temp-months-seasons.csv")


# print message that data downloads were successful
print("datasets downloaded successfully")

datasets downloaded successfully


In [96]:
temp_seas = pd.read_csv("data/avg-temp-months-seasons.csv")

In [97]:
print(temp_seas)

   months   temp seasons
0     Jan   0.00  Winter
1     Feb   2.00  Winter
2     Mar   5.00  Spring
3     Apr   9.56  Spring
4     May  14.39  Spring
5    June  19.56  Summer
6    July  22.78  Summer
7     Aug  21.72  Summer
8    Sept  16.72    Fall
9     Oct  11.61    Fall
10    Nov   4.89    Fall
11    Dec   0.99  Winter
